title: "[FoxVox] - Which news are real?"
description: "A chrome extension powered by gpt-4o made by Palisade Research to interactively demonstrate capabilities of AI for automated disinformation at scale."
theme: "jekyll-theme-cayman"
